# Generated by Django 4.2.25 on 2025-10-27 03:27

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.file_upload_path)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("reference_count", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FileReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_hash"], name="files_file_file_ha_868749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_type"], name="files_file_file_ty_2d7e73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["uploaded_at"], name="files_file_uploade_726d10_idx"
            ),
        ),
    ]
