# Generated by Django 4.2.25 on 2025-10-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash', 'file_type'], name='files_file_file_ha_1bdcc1_idx'),
        ),
    ]
